#!/bin/bash

# Pickup 'pip install --user binaries'.
PATH=$PATH:$HOME/.local/bin

export BZR_PLUGIN_PATH=$(python -c 'import site; print site.USER_SITE')/bzrlib/plugins

twistd \
    --logfile ~/log/twistd.log \
    --pidfile ~/run/twistd.pid \
    --rundir ~/run/ \
    --python ~/run/buildbot.tac
